name: /mnt/Stuffs/Projects/fromScratch/pytorch_vqgan/env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotlipy=0.7.0=py37h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.07.19=h06a4308_0
  - certifi=2022.6.15=py37h06a4308_0
  - cffi=1.15.1=py37h74dc2b5_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=37.0.1=py37h9ce1e76_0
  - cudatoolkit=11.6.0=hecad31d_10
  - ffmpeg=4.2.2=h20bf706_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - idna=3.3=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h7f8727e_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libidn2=2.3.2=h7f8727e_0
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h2818925_1
  - libunistring=0.9.10=h27cfd23_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - lz4-c=1.9.3=h295c915_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h51133e4_0
  - ncurses=6.3=h5eee18b_3
  - nettle=3.7.3=hbbd107a_1
  - numpy=1.21.5=py37h6c91a56_3
  - numpy-base=1.21.5=py37ha15fc14_3
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1q=h7f8727e_0
  - pillow=9.2.0=py37hace64e9_1
  - pip=22.1.2=py37h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py37_1
  - python=3.7.13=h12debd9_0
  - python_abi=3.7=2_cp37m
  - pytorch=1.12.1=py3.7_cuda11.6_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - readline=8.1.2=h7f8727e_1
  - requests=2.28.1=py37h06a4308_0
  - setuptools=61.2.0=py37h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.39.2=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.12.1=py37_cu116
  - torchvision=0.13.1=py37_cu116
  - typing_extensions=4.3.0=py37h06a4308_0
  - urllib3=1.26.11=py37h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - x264=1!157.20191217=h7b6447c_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - aim==3.12.2
    - aim-ui==3.12.2
    - aimrecords==0.0.7
    - aimrocks==0.2.1
    - aiofiles==0.8.0
    - albumentations==1.2.1
    - alembic==1.8.1
    - attrs==22.1.0
    - base58==2.0.1
    - beautifulsoup4==4.11.1
    - cachetools==5.2.0
    - click==8.1.3
    - codecov==2.1.12
    - coverage==6.4.3
    - exceptiongroup==1.0.0rc8
    - fastapi==0.67.0
    - filelock==3.8.0
    - google-api-core==2.8.2
    - google-api-python-client==2.56.0
    - google-auth==2.10.0
    - google-auth-httplib2==0.1.0
    - googleapis-common-protos==1.56.4
    - greenlet==1.1.2
    - grpcio==1.47.0
    - h11==0.13.0
    - httplib2==0.20.4
    - hypothesis==6.54.3
    - imageio==2.21.1
    - importlib-metadata==4.12.0
    - importlib-resources==5.9.0
    - iniconfig==1.1.1
    - jinja2==3.1.2
    - joblib==1.1.0
    - lpips==0.1.4
    - mako==1.2.1
    - markupsafe==2.1.1
    - networkx==2.6.3
    - opencv-python-headless==4.6.0.66
    - packaging==21.3
    - pandas==1.3.5
    - pluggy==1.0.0
    - protobuf==3.20.0
    - psutil==5.9.1
    - py==1.11.0
    - py3nvml==0.2.7
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydantic==1.9.2
    - pyparsing==3.0.9
    - pytest==7.1.2
    - pytest-cov==3.0.0
    - python-dateutil==2.8.2
    - pytz==2022.2.1
    - pywavelets==1.3.0
    - pyyaml==6.0
    - qudida==0.0.4
    - restrictedpython==5.2
    - rsa==4.9
    - scikit-image==0.19.3
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - sortedcontainers==2.4.0
    - soupsieve==2.3.2.post1
    - sqlalchemy==1.4.40
    - starlette==0.14.2
    - threadpoolctl==3.1.0
    - tifffile==2021.11.2
    - tomli==2.0.1
    - torch-summary==1.4.5
    - tqdm==4.64.0
    - uritemplate==4.1.1
    - uvicorn==0.18.2
    - xmltodict==0.13.0
    - zipp==3.8.1
prefix: /mnt/Stuffs/Projects/fromScratch/pytorch_vqgan/env
