name: base
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - brotlipy=0.7.0=py37h27cfd23_1003
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.6.15=ha878542_0
  - certifi=2022.6.15=py37h89c1867_0
  - cffi=1.15.0=py37hd667e15_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - conda=4.13.0=py37h89c1867_1
  - conda-content-trust=0.1.1=pyhd3eb1b0_0
  - conda-package-handling=1.8.1=py37h7f8727e_0
  - cryptography=36.0.0=py37h9ce1e76_0
  - cudatoolkit=11.6.0=hecad31d_10
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h0708190_1
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - idna=3.3=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h166bdaf_1
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.17=h166bdaf_0
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libtiff=4.2.0=hf544144_3
  - libwebp-base=1.2.2=h7f98852_1
  - lz4-c=1.9.3=h9c3ff4c_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h402132d_0
  - mkl_fft=1.3.1=py37h3e078e5_1
  - mkl_random=1.2.2=py37h219a48f_0
  - ncurses=6.3=h7f8727e_2
  - nettle=3.6=he412f7d_0
  - numpy=1.21.5=py37h6c91a56_3
  - numpy-base=1.21.5=py37ha15fc14_3
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1o=h166bdaf_0
  - pip=21.2.2=py37h06a4308_0
  - pycosat=0.6.3=py37h27cfd23_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py37_1
  - python=3.7.13=h12debd9_0
  - python_abi=3.7=2_cp37m
  - pytorch=1.12.1=py3.7_cuda11.6_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - readline=8.1.2=h7f8727e_1
  - requests=2.27.1=pyhd3eb1b0_0
  - ruamel_yaml=0.15.100=py37h27cfd23_0
  - setuptools=61.2.0=py37h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.2=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - torchaudio=0.12.1=py37_cu116
  - torchvision=0.13.1=py37_cu116
  - tqdm=4.63.0=pyhd3eb1b0_0
  - typing_extensions=4.3.0=pyha770c72_0
  - urllib3=1.26.8=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.12=h7f8727e_1
  - zstd=1.5.0=ha95c52a_0
  - pip:
    - absl-py==1.2.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - albumentations==1.2.1
    - astroid==2.11.7
    - async-timeout==4.0.2
    - asynctest==0.13.0
    - attrs==22.1.0
    - beautifulsoup4==4.11.1
    - black==22.6.0
    - cachetools==5.2.0
    - click==8.1.3
    - coloredlogs==15.0.1
    - commonmark==0.9.1
    - cycler==0.11.0
    - dill==0.3.5.1
    - einops==0.4.1
    - filelock==3.7.1
    - flatbuffers==2.0
    - fonttools==4.34.4
    - frozenlist==1.3.1
    - fsspec==2022.7.1
    - gdown==4.5.1
    - google-auth==2.10.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.47.0
    - humanfriendly==10.0
    - imageio==2.21.0
    - importlib-metadata==4.12.0
    - imutils==0.5.4
    - iniconfig==1.1.1
    - isort==5.10.1
    - joblib==1.1.0
    - kiwisolver==1.4.4
    - lazy-object-proxy==1.7.1
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.5.2
    - mccabe==0.7.0
    - mpmath==1.2.1
    - multidict==6.0.2
    - mypy-extensions==0.4.3
    - networkx==2.6.3
    - oauthlib==3.2.0
    - onnx==1.12.0
    - onnxruntime==1.12.1
    - onnxruntime-gpu==1.12.1
    - opencv-python==4.6.0.66
    - opencv-python-headless==4.6.0.66
    - packaging==21.3
    - pandas==1.3.5
    - pathspec==0.9.0
    - pillow==9.2.0
    - platformdirs==2.5.2
    - pluggy==1.0.0
    - protobuf==3.19.4
    - py==1.11.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.9.1
    - pydeprecate==0.3.2
    - pydocstyle==6.1.1
    - pygments==2.12.0
    - pylint==2.14.5
    - pyparsing==3.0.9
    - pytest==7.1.2
    - python-dateutil==2.8.2
    - pytorch-lightning==1.7.0
    - pytz==2022.1
    - pywavelets==1.3.0
    - pyyaml==6.0
    - qudida==0.0.4
    - requests-oauthlib==1.3.1
    - rich==12.5.1
    - rsa==4.9
    - scikit-image==0.19.3
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - seaborn==0.11.2
    - snowballstemmer==2.2.0
    - soupsieve==2.3.2.post1
    - sympy==1.10.1
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - threadpoolctl==3.1.0
    - tifffile==2021.11.2
    - tomli==2.0.1
    - tomlkit==0.11.1
    - torch-summary==1.4.5
    - torchmetrics==0.9.3
    - typed-ast==1.5.4
    - vit-pytorch==0.35.8
    - werkzeug==2.2.1
    - wrapt==1.14.1
    - yarl==1.8.1
    - zipp==3.8.1
prefix: /home/nightfury/Documents/miniconda3
